name: Synapse Environment Template

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        default: "dev"
        description: "Specifies the environment of the deployment."
      init_project_version:
        required: false
        type: string
        default: "main"
        description: "Specifies the version of the Init project."
      target_synapse_workspace_name:
        required: true
        type: string
        description: "Specifies the name of the target synapse workspace."
      target_synapse_workspace_resource_group_name:
        required: true
        type: string
        description: "Specifies the resource group name of the target synapse workspace."
      deployment:
        required: true
        type: boolean
        default: false
        description: "Specifies whether the deployment job should be executed."
    secrets:
      TENANT_ID:
        required: true
        description: "Specifies the tenant id of the deployment."
      CLIENT_ID:
        required: true
        description: "Specifies the client id."
      CLIENT_SECRET:
        required: true
        description: "Specifies the client secret."
      SUBSCRIPTION_ID:
        required: true
        description: "Specifies the client id."
      PAT:
        required: true
        description: "Specifies the GitHub PAT."

env:
  SOURCE_SYNAPSE_WORKSPACE_NAME: "synw-spf-0003-dev-we1-01"
  SYNAPSE_ARTIFACTS_PATH: "code/synapse"
  SYNAPSE_DEPLOYMENT_SCRIPT_PATH: "code/scripts"

jobs:
  validation:
    name: Synapse Validation
    runs-on: [self-hosted]
    continue-on-error: false
    needs: []

    steps:
      # Check Out Repository
      - name: Check Out Repository
        id: checkout_repository
        uses: actions/checkout@v3
        with:
          repository: Financial-Data-Pool/simplifi-db-development
          ref: ${{ inputs.init_project_version }}
          token: ${{ secrets.PAT }}

      # Validate Synapse Artifacts
      - name: Validate Synapse Artifacts
        id: validation_synapse
        uses: azure/synapse-workspace-deployment@V1.7.0
        with:
          TargetWorkspaceName: ${{ inputs.target_synapse_workspace_name }}
          ArtifactsFolder: ${{ env.SYNAPSE_ARTIFACTS_PATH }}
          operation: "validate"
          deployManagedPrivateEndpoint: false
          DeleteArtifactsNotInTemplate: false

  deploy:
    name: Synapse Deployment
    runs-on: [self-hosted]
    continue-on-error: false
    environment: ${{ inputs.environment }}
    needs: [validation]

    steps:
      # Check Out Repository
      - name: Check Out Rollout Repository
        id: checkout_repository_rollout
        uses: actions/checkout@v3
        with:
          path: rollout

      # Check Out Repository
      - name: Check Out Synapse Repository
        id: checkout_repository_synapse
        uses: actions/checkout@v3
        with:
          repository: Financial-Data-Pool/simplifi-db-development
          ref: ${{ inputs.init_project_version }}
          token: ${{ secrets.PAT }}
          path: synapse

      # Login to Azure
      - name: Azure Login
        id: azure_login
        uses: azure/login@v1
        with:
          creds:  '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'
          enable-AzPSSession: true

      # Install Required Modules
      - name: Install Required Modules
        id: install_modules
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module Az -ErrorAction Stop
        shell: pwsh
        working-directory: "synapse/${{ env.SYNAPSE_DEPLOYMENT_SCRIPT_PATH }}"

      # Synapse Pre-Processing Step
      - name: Synapse Pre-Processing Step
        id: synapse_preprocessing
        run: |
          ./SynapseRolloutPreprocessing.ps1 `
            -SubscriptionId "${{ secrets.SUBSCRIPTION_ID }}" `
            -SynapseWorkspaceName "${{ inputs.target_synapse_workspace_name }}" `
            -CheckPastDaysOfPipelineRuns 1
        shell: pwsh
        working-directory: "synapse/${{ env.SYNAPSE_DEPLOYMENT_SCRIPT_PATH }}"

      # Deploy Synapse Artifacts
      - name: Deploy Synapse Artifacts
        id: deployment_synapse
        uses: azure/synapse-workspace-deployment@V1.7.0
        with:
          TargetWorkspaceName: ${{ inputs.target_synapse_workspace_name }}
          resourceGroup: ${{ inputs.target_synapse_workspace_resource_group_name }}
          TemplateFile: "synapse/${{ env.SOURCE_SYNAPSE_WORKSPACE_NAME }}/TemplateForWorkspace.json"
          ParametersFile: "rollout/tests/e2e/synapseConfig/params.synapse.json"
          # ArtifactsFolder:
          operation: "deploy"
          deployManagedPrivateEndpoint: false
          # OverrideArmParameters:
          DeleteArtifactsNotInTemplate: false
          Environment: "Azure Public"
          tenantId: ${{ secrets.TENANT_ID }}
          subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
          clientId: ${{ secrets.CLIENT_ID }}
          clientSecret: ${{ secrets.CLIENT_SECRET }}
          managedIdentity: false

      # # Synapse Post-Processing Step
      # - name: Synapse Post-Processing Step
      #   id: synapse_postprocessing
      #   run: |
      #     ./SynapseRolloutPostprocessing.ps1 `
      #       -SubscriptionId "${{ secrets.SUBSCRIPTION_ID }}" `
      #       -SynapseWorkspaceName "${{ inputs.target_synapse_workspace_name }}" `
      #       -TriggerNames "${{ steps.synapse_preprocessing.outputs.triggerNames }}"
      #   shell: pwsh
      #   working-directory: "synapse/${{ env.SYNAPSE_DEPLOYMENT_SCRIPT_PATH }}"

      # Log out from Azure
      - name: Log out from Azure
        id: azure_logout
        run: |
          az logout
