name: Terraform Deployment
on:
  push:
    branches:
      - main
    paths:
      - "code/terraform/**"
      - ".github/workflows/deployment"

  pull_request:
    branches:
      - main
    paths:
      - "code/terraform/**"
      - ".github/workflows/deployment"

jobs:
  terraform:
    uses: ./.github/workflows/_terraformEnvironmentTemplate.yml
    name: "Terraform Deployment"
    with:
      environment: "dev"
      working_directory: "./code/terraform"
      subscription_id: "8f171ff9-2b5b-4f0f-aed5-7fa360a1d094"
      export_terraform_outputs: false
    secrets:
      TENANT_ID: ${{ secrets.TENANT_ID }}
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
